Automated tests
Police-Data-Accessibility-Project/data-sources-app pull request #177
Opened 2024-01-10 17:10 UTC by mbodeantor

Run API checks every 15 min

2024-01-10 18:22 UTC, josh-chamberlain commented
nice. when these run, where would we see the test results? the `actions` section of the repo?

2024-01-10 18:53 UTC, mbodeantor commented
@josh-chamberlain yeah, once I'm sure they work, I want to add the discord webhook too for fails

2024-01-11 17:27 UTC, josh-chamberlain requested changes
looks good aside from those 2 lil changes

2024-01-11 21:57 UTC, mbodeantor commented on regular_api_checks.py
> +def test_get_archives():
Adding docs: https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/454/api/endpoints/data-sources-database

2024-01-12 19:37 UTC, merged