⚡️ feat(middleware): Add functionality to cache homepage search results
Police-Data-Accessibility-Project/data-sources-app pull request #317
Opened 2024-06-02 22:30 UTC by maxachis

#### Fixes

* Partially addresses https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/53

#### Description

- Added new middleware file `homepage_search_cache.py` to handle caching of search results for agencies without homepage URLs
- Added SQL queries to retrieve agencies without homepage URLs and update the search cache
- Implemented functions to get agencies without homepage URLs and update search cache
- Added new resource `HomepageSearchCache` in `resources/HomepageSearchCache.py` to handle API requests for retrieving and updating search cache

#### Testing

* Not sure! I could set up an integration test for it, or we could deploy it and see if it works/doesn't break things when I reconfigure the data source identification code to work with it, or try some unknown third option.

#### Performance

* Creation of new endpoint. As untested, performance impact unknown, but likely minimal. 

#### Docs

* TODO

2024-06-03 00:09 UTC, josh-chamberlain requested changes
nice! could you please add a section in the docs for this endpoint? that will also take care of PR review—if a reviewer can use the doc to hit the endpoint successfully, that's good.

2024-06-03 22:03 UTC, maxachis commented
@josh-chamberlain Done! Found here: https://github.com/Police-Data-Accessibility-Project/docs/pull/15

Note that I am _very_ unfamiliar with this format, and did not know how to test it. Additionally, because it was fairly redundant, I used ChatGPT to make the first draft. I anticipate this will need editing in the near future, especially as we test it; I'm just not sure how to do that at the moment.

2024-06-06 03:11 UTC, josh-chamberlain commented
@maxachis 

1. on docs formatting, the reason it looks weird like that is because we're using gitbook and it's their ~proprietary format. I find making these changes is much easier in the WYSIWYG editor, which is something I hate to say so it _must_ be true. You should be in the gitbook org, and this link will take you to the edit view: https://app.gitbook.com/@pdap/s/pdap/

It's a little weird at first, but the formatting will make a _lot_ more sense.


2. I should have thought of this before—did you consider modifying the agencies endpoint to accept an arg for the blank homepage, rather than creating a new endpoint?

2024-06-06 17:14 UTC, maxachis commented
> @maxachis
> 
> 1. on docs formatting, the reason it looks weird like that is because we're using gitbook and it's their ~proprietary format. I find making these changes is much easier in the WYSIWYG editor, which is something I hate to say so it _must_ be true. You should be in the gitbook org, and this link will take you to the edit view: https://app.gitbook.com/@pdap/s/pdap/
> 
> It's a little weird at first, but the formatting will make a _lot_ more sense.
> 
> 2. I should have thought of this before—did you consider modifying the agencies endpoint to accept an arg for the blank homepage, rather than creating a new endpoint?

@josh-chamberlain 
For 1: Is that mentioned somewhere in the documentation? Might be useful to add if not. 
For 2: The challenge is that this is specifically for recording a multitude of _possible_ homepages, without a clear idea of which is most viable. Currently, it defaults to finding 10 possible homepages per agency. So we can't easily update the agencies row itself.

2024-06-10 16:45 UTC, josh-chamberlain commented
@maxachis for 1. I left a comment on the docs PR
2. oh, right—mixed up the context! thanks

2024-06-13 01:16 UTC, maxachis commented
@josh-chamberlain Made a Docs Pull Requests, which I've linked in the main post!

2024-06-13 15:17 UTC, josh-chamberlain commented
@maxachis thank you! I approved, since the button was just looking at me, but if you are making docs in support of a PR I do not mind if you just reference + self-merge.

2024-06-13 15:18 UTC, josh-chamberlain approved these changes

2024-06-15 21:27 UTC, merged