Update font to public sans
Police-Data-Accessibility-Project/data-sources-app pull request #373
Opened 2024-07-26 21:47 UTC by phillitrOSU

Feel free to leap-frog over me if I'm taking too long to understand this task. In this PR I just removed the "Franklin" google font href, and replaced it with Public Sans. Is that it?

This is my first time working with Vue so while I was able to get the data-sources-app development environment working, I was not able to get it connected my local "design-system-main" files. I don't see any changes occurring from the font change in the index.html file. Seems like there are more CSS overrides elsewhere?

If this is not what you need and you think you could give me more direction I'd be happy to give it a go next week! I'm a new CS student with a lot to learn and eager to do it : )! But if me trying to help is more of a nuisance, I understand. Really curious about the project!

Cheers,

Trevor

2024-07-29 18:42 UTC, josh-chamberlain requested changes
Thank you for jumping in @phillitrOSU ! You will also need to install the latest version of the `pdap-design-system` package: https://github.com/Police-Data-Accessibility-Project/design-system/releases/tag/v3.0.0

To do that, you can run:

```
npm install pdap-design-system@latest
```
or
```
npm install pdap-design-system@3.0.0
```

The package.json should update, too. It's a big version jump, but there shouldn't be many other visual changes.

It makes sense that you wouldn't see changes until you do that—but the fonts are quite similar, so be sure to check which one's actually being rendered.

2024-07-30 14:36 UTC, phillitrOSU commented
Thanks for the tip! After several tries, I am getting this behavior. Upgrading to design system 3.0.0 renders a blank page. If I downgrade back to design system 2.5.0, the page renders as expected. Is there another place in the code I would need to update before design system 3.0.0 would work?
<img width="1925" alt="Screenshot 2024-07-30 at 8 32 53 AM" src="https://github.com/user-attachments/assets/f70514b1-1188-437e-be1f-1c365e1fcec6">
<img width="1917" alt="Screenshot 2024-07-30 at 8 33 27 AM" src="https://github.com/user-attachments/assets/830d5c03-ee46-42d6-a8f3-ff480e2baef2">

2024-07-30 16:29 UTC, josh-chamberlain commented
@phillitrOSU hmm, I see your branch has the most recent changes. Unfortunately, I'm not sure! @joshuagraber any ideas?

2025-03-03 21:14 UTC, josh-chamberlain commented
@phillitrOSU thanks again for your contribution; I'm closing this because we closed it somewhere along the way on the v2 fork, which just merged to main.

2025-03-03 21:14 UTC, closed without merging