Feature/data source static view
Police-Data-Accessibility-Project/data-sources-app pull request #58
Opened 2023-09-27 20:16 UTC by kalenluciano

#### Fixes

* Add a new route in the backend to get all info on a specific data source by its ID
* Creates a page to display all info on a specific data source
* Make the data source detail button navigate to the data source static view page
* Separate out the footer and NavBar into their own components
* Add two NavBars (one with just the logo and one with links) that conditionally render depending on the current page
* Change the global.css import to fix a random bug where the CSS would sometimes stop applying to the site

#### Description
The primary purpose of this PR was to add a Data Source Static View page that displays all the available (non-PII) info for a data source. In addition to adding a page, I added a separate route in the backend to get all the necessary info to display. I also altered some formatting and styling, both on the Data Source Static View page and with the NavBars.

2023-10-10 15:07 UTC, joshuagraber requested changes
Looks great! Just a couple suggestions and questions around component naming and error handling.

2023-10-10 21:05 UTC, kalenluciano commented on client/src/App.vue
> +  <NavBarLogo v-else />
Makes sense to me, added this in

2023-10-10 22:27 UTC, kalenluciano reviewed
Thanks for the feedback! I implemented these changes and will push an updated PR shortly.

2023-10-10 22:27 UTC, kalenluciano commented on client/src/pages/DataSourceStaticView.vue
> +      <div class="data-detail-section">
Great idea! It definitely felt redundant typing it all out

2023-10-10 22:27 UTC, kalenluciano commented on client/src/pages/DataSourceStaticView.vue
> +      const res = await axios.get(`${process.env.VUE_APP_BASE_URL}/data-sources/${this.id}`, {headers})
I added some error handling for this

2023-10-13 14:55 UTC, joshuagraber submitted a review, later dismissed

2023-10-13 15:58 UTC, mbodeantor commented
Are we still not able to run this locally? I'm getting an axios error still

2023-10-13 16:34 UTC, kalenluciano commented
I'm getting the same issue. I think I'm going to move these env variables to a globals.js file instead. I'll push updates shortly!

2023-10-13 16:55 UTC, josh-chamberlain commented on client/src/pages/DataSourceStaticView.vue
> +      <button class="button">Edit</button>
(totally fine if it's removed until the edit function is possible, thanks for sticking to the wireframe)

2023-10-13 17:09 UTC, mbodeantor commented
I think you can just remove the hardcoded variable for BASE_URL since it is specified for each env in DigitalOcean

2023-10-13 17:12 UTC, mbodeantor commented
Also I don't think "Formats available" is iterating correctly
![Screenshot 2023-10-13 at 1 12 01 PM](https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/96697114/5227cf65-e2bd-45e6-915a-b12ef35e208d)

2023-10-13 21:10 UTC, joshuagraber commented
Hey @kalenluciano @mbodeantor I checked out [this commit](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/58/commits/82ea4b6367f8f7b7634137f908c765c05426deeb) (the one prior to adding these as js globals), and it's working for me.

I've noticed that I need to re-set the flask env vars every time I start the app, maybe that's it? I added a `zsh` func/alias to activate venv, install python requirements, and set the env stuff. Can send to you in Discord if you're interested.

The Formats available section does need fixing though.

2023-10-19 21:32 UTC, kalenluciano commented
I changed the globals.js back to env variables based on our conversation earlier this week. 

Re: > Also I don't think "Formats available" is iterating correctly ![Screenshot 2023-10-13 at 1 12 01 PM](https://user-images.githubusercontent.com/96697114/274981011-5227cf65-e2bd-45e6-915a-b12ef35e208d.png)

I made a fix to this in the backend, but since the frontend app is pointing to live deployed version, you won't see this change. To test the change, you'll have to change VUE_APP_BASE_URL to localhost:5000 and run the backend

2023-10-24 20:51 UTC, mbodeantor approved these changes
Awesome, looks good to me!

2023-10-24 20:52 UTC, merged